 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/success_stories", type: :request do
  # SuccessStory. As you add validations to SuccessStory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SuccessStory.create! valid_attributes
      get success_stories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      success_story = SuccessStory.create! valid_attributes
      get success_story_url(success_story)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_success_story_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      success_story = SuccessStory.create! valid_attributes
      get edit_success_story_url(success_story)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SuccessStory" do
        expect {
          post success_stories_url, params: { success_story: valid_attributes }
        }.to change(SuccessStory, :count).by(1)
      end

      it "redirects to the created success_story" do
        post success_stories_url, params: { success_story: valid_attributes }
        expect(response).to redirect_to(success_story_url(SuccessStory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SuccessStory" do
        expect {
          post success_stories_url, params: { success_story: invalid_attributes }
        }.to change(SuccessStory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post success_stories_url, params: { success_story: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested success_story" do
        success_story = SuccessStory.create! valid_attributes
        patch success_story_url(success_story), params: { success_story: new_attributes }
        success_story.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the success_story" do
        success_story = SuccessStory.create! valid_attributes
        patch success_story_url(success_story), params: { success_story: new_attributes }
        success_story.reload
        expect(response).to redirect_to(success_story_url(success_story))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        success_story = SuccessStory.create! valid_attributes
        patch success_story_url(success_story), params: { success_story: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested success_story" do
      success_story = SuccessStory.create! valid_attributes
      expect {
        delete success_story_url(success_story)
      }.to change(SuccessStory, :count).by(-1)
    end

    it "redirects to the success_stories list" do
      success_story = SuccessStory.create! valid_attributes
      delete success_story_url(success_story)
      expect(response).to redirect_to(success_stories_url)
    end
  end
end
